version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@123"
    ports:
      - "1433:1433"
  # Cấu hình cho Redis
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: always